= Nexposegli
Christian Kyony <ckyony@changamuka.com>
v0.0.1, 3 February 2017



For security engineers
Who needs to interact with a Rapid7 Nexpose console,
The *nexposegli* gem is a Git like command line utility
That provides the ability to:

- create a new site,
- add an IP to the site,
- perform a scan against the site using a defined/passed scan template,
- produce a reports for vulnerabilitie0s, installed software, and policy compliance.
- to delete in bulk more than 1000 assets in a given site
- etc

Unlike the Nexposecli gem and other alternatives,
*nexposecli* is designed as command suite a la GIT.


== Installation

=== From Rubygems

----
$ gem install nexposegli
----

=== From source code

- If you have access to the Internet, obtain the source code from Github repository.

  $ git clone https://github.com/rhc/nexposegli.git

- Access the source code folder directory.

  $ cd nexposegli

- Install the dependencies

  $ bin/setup

- Install the gem in your local machine

  $ bundle exec rake install

- Run the test suite

  $ rake test

== Usage

You can get help on available commands.

  $ ng help

  Commands:
    ng --version, -v   # Print the version
    ng help [COMMAND]  # Describe available commands or one specific command


List all active scans

  ng scan list

Run an adhoc sql query and export via csv

  ng --run --QUERY --config ./lab.yaml --sql "select * from dim_asset"

or for more complex sql queries, put the sql into a file and run

  ng --run --QUERY --config ./lab.yaml --sqlfile ./new_assets.sql

NOTE: Consider reviewing the SQL examples and reports available here: https://community.rapid7.com/community/nexpose/report-templates

List all reports defined

  ng report list

Request the console's version details

  ng console --COMMAND "ver"

Run an adhoc scan for a single ip or network cidr-noted range ( --id )

  ng --config ./lab.yaml --create --SCAN --id 1 --range 192.168.42.103/32

how to add a new custom role for configuration within the console ui, based on a copy of existing role

  ng --config ./lab.yaml --create --ROLE -n security-manager --description "New Role Name" --newname new-short-name

how to add a new user, with default password of "nxpassword" until moved to yaml config is supported

  ng  --config ./lab.yaml --create --USER --name <username> --fullname "Full Name"

how to export packaged scan data in a single zip file

  ng --config ./lab.yaml --SCAN --update --scanpath ./ --action export --id <scan id>

where ./lab.yaml consists of the following:

config:
   server: 10.10.10.10
   user: nxuser
   password: password

NOTE: Be sure to use your Nexpose Console's ip address and credentials







== License

The gem is available as open source
under the terms of the [MIT License](http://opensource.org/licenses/MIT).



