= Nexpose Security Console
Christian Kyony <ckyony@changamuka.com>
v0.0.1, 3 February 2017


For security engineers
who needs to interact with a Rapid7 Nexpose console,
the *nexpose-security-console* gem is a Git like command line utility
that provides the ability to:

- create a new site,
- add an IP to the site,
- perform a scan against the site usinsc a defined/passed scan template,
- produce a reports for vulnerabilitie0s, installed software, and policy compliance.
- to delete in bulk more than 1000 assets in a given site
- etc

Unlike the Nexposecli gem and other alternatives,
*nexpose-security-consolei* is designed as command suite a la GIT.


== Personal scratch

I need to delete ~ 100 thousands assets from a group asset.
The web GUI only allows to delete 500 at a time.
Hence, nexpose-security-console was born.


== Installation

=== From Rubygems

----
$ gem install nexpose-security-console
----

=== From source code

- If you have access to the Internet, obtain the source code from Github repository.

  $ git clone https://github.com/rhc/nexpose-security-console.git

- Access the source code folder directory.

  $ cd nexpose-security-console

- Install the dependencies

  $ bin/setup

- Install the gem in your local machine

  $ bundle exec rake install

- Run the test suite

  $ rake test

== Usage

You can get help on available commands.

  $ nsc help

  Commands:
    nsc --version, -v   # Print the version
    nsc help [COMMAND]  # Describe available commands or one specific command


List all active scans

  nsc scan list

Run an adhoc sql query and export via csv

  nsc reports --config ./lab.yaml --sql "select * from dim_asset"

or for more complex sql queries, put the sql into a file and run

  nsc reports --config ./lab.yaml --sqlfile ./new_assets.sql


List all reports defined

  nsc reports

Request the console's version details

  nsc console --COMMAND "ver"

Run an adhoc scan for a single ip or network cidr-noted range ( --id )

  nsc scans create --range 192.168.42.103/32

how to add a new custom role for configuration within the console ui, based on a copy of existinsc role

  nsc roles -n security-manager --description "New Role Name" --newname new-short-name

how to add a new user, with default password of "nxpassword" until moved to yaml config is supported

  nsc users create  --name <username> --fullname "Full Name"

how to export packaged scan data in a single zip file

  nsc scan  --update --scanpath ./ --action export --id <scan id>


== Configuration

----
# ~/lab.yaml consists of the following:

config:
   server: 10.10.10.10
   user: nxuser
   password: password
----

NOTE: Be sure to use your Nexpose Console's ip address and credentials







== License

The gem is available as open source under the terms of the
http://opensource.org/licenses/MIT[MIT License].



