#!/usr/bin/env ruby
require 'gli'
require "nexpose-security-console"

include GLI::App

program_desc 'CLI to interface with Nexpose Security Console'
version NexposeSecurityConsole::VERSION

subcommand_option_handling :normal
arguments :strict

desc 'Describe some switch here'
switch [:s,:switch]

desc 'Describe some flag here'
default_value 'the default'
arg_name 'The name of the argument'
flag [:f,:flagname]

desc 'Manage sites'
arg_name 'Describe arguments to sites here'
command :sites do |c|
  c.desc 'Describe a switch to sites'
  c.switch :s

  c.desc 'Describe a flag to sites'
  c.default_value 'default'
  c.flag :f
  c.action do |global_options,options,args|

    # Your command logic here
    # If you have any errors, just raise them
    # raise "that command made no sense"

    puts "sites command ran"
  end
end

desc 'Manage asset groups'
command :groups do |c|
  c.desc 'List asset groups'
  c.command :list do |ls|
    ls.action do |global_options,options,args|
      puts "list asset groups"
    end
  end
  c.default_command :list


end

desc 'Manage assets'
arg_name 'Describe arguments to assets here'
command :assets do |c|
  c.action do |global_options,options,args|
    puts "assets command ran"
  end
end

desc 'Manage reports'
arg_name 'Describe arguments to reports here'
command :reports do |c|
  c.action do |global_options,options,args|
    puts "reports command ran"
  end
end

pre do |global,command,options,args|
  # Pre logic here
  # Return true to proceed; false to abort and not call the
  # chosen command
  # Use skips_pre before a command to skip this block
  # on that command only
  true
end

post do |global,command,options,args|
  # Post logic here
  # Use skips_post before a command to skip this
  # block on that command only
end

on_error do |exception|
  # Error logic here
  # return false to skip default error handling
  true
end

exit run(ARGV)
